### ISSUE TITLE
Disallow cuda-python 12.6.1 / 11.8.4

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#116]
Due to a bug in cuda-python we must disallow cuda-python 12.6.1 and 11.8.4. https://github.com/NVIDIA/cuda-python/issues/215

We expect 12.6.2 and 11.8.5 to correct this bug. I will file PRs to all of RAPIDS to pin `cuda-python !=12.6.1` / `!=11.8.4`.

**Comment by jameslamb** [comment]
All of the PRs updating pins to skip these versions have been merged, and this issue is no longer affecting RAPIDS CI.

The only remaining open item is the `rapids-reviser` PR (https://github.com/rapidsai/rapids-reviser/pull/56). That isn't a critical part of this, so I'm closing this issue in the interest of narrowing down the list of what's left to be done for 24.12.
